CREATE TABLE CENTROS_FORENSES(
    ID VARCHAR(100) PRIMARY KEY,
    NOMBRE VARCHAR(100) PRIMARY KEY,
    PAIS VARCHAR(100),
    NIVEL_SEGURIDAD INTEGER(4),
    SANCHEZJOEL VARCHAR(11)
    );

CREATE TABLE MUESTRAS_FORENSES(
    ID VARCHAR(100) PRIMARY KEY,
    CODIGO_CASO INTEGER(100),
    TIPO_MUESTRA VARCHAR(100),
    FECHA_RECOGIDA VARCHAR(100),
    ESTADO_CUSTODIA VARCHAR(100),
    FK_CENTRO_ID VARCHAR(100),
    SANCHEZJOEL VARCHAR(11),

    CONSTRAINT fk_CENTROS_FORENSES FOREIGN KEY (FK_CENTRO_ID)
        REFERENCES CENTROS_FORENSES(ID)
);

CREATE TABLE INFORMES_FORENSES(
    ID VARCHAR(100) PRIMARY KEY,
    ADN_POSITIVO VARCHAR(100),
    NIVEL_RIESGO INTEGER(100),
    CONCLUSION VARCHAR(200),
    FK_MUESTRA_ID UNIQUE,
    SANCHEZJOEL VARCHAR(11),

    CONSTRAINT
    CONSTRAINT fk_MUETRAS_FORENSES FOREIGN KEY (FK_MUESTRA_ID)
        REFERENCES MUESTRAS_FORENSES (ID)
);