INSERT INTO CENTROS_FORENSES(
'C1', 'CENTRO ARRIBA', 'ESPANYA', 1, 'SANCHEZJOEL'
);
INSERT INTO CENTROS_FORENSES(
'C2', 'CENTRO ABAJO', 'FRANCIA', 2, 'SANCHEZJOEL'
);

INSERT INTO MUESTRAS_FORENSES(
'M1', 001, 'HUELLA', '01/01/2026', 'RECOGIDO', 'C1', 'SANCHEZJOEL'
);
INSERT INTO MUESTRAS_FORENSES(
'M2', 002, 'PELO', '02/01/2026', 'EXAMINADO', 'C2', 'SANCHEZJOEL'
);

INSERT INTO INFORMES_FORENSES(
'I1', 'POSITIVO', 1, 'CONCLUYENTE', 'M1', 'SANCHEZJOEL'
);
INSERT INTO INFORMES_FORENSES(
'I2', 'NEGATIVO', 2, 'NO_CONCLUYENTE', 'M2', 'SANCHEZJOEL'
);