SELECT * FROM CENTROS_FORENSES;
SELECT * FROM MUESTRAS_FORENSES;
SELECT * FROM INFORMES_FORENSES;

SELECT * FROM CENTROS_FORENSES WHERE PAIS = 'ESPANYA';
SELECT * FROM MUESTRAS_FORENSES WHERE TIPO_MUESTRA = 'PELO';

SELECT c.NOMBRE, m.TIPO_MUESTRA
FROM MUESTRAS_FORENSES m
INNER JOIN CENTROS_FORENSES c ON m.FK_CENTRO_ID = c.ID;

SELECT c.NOMBRE, m.TIPO_MUESTRA, i.CONCLUSION
FROM SATELITES INFORMES_FORENSES i
INNER JOIN MUESTRAS_FORENSES m ON i.FK_MUESTRA_ID = m.ID
INNER JOIN CENTROS_FORENSES c ON m.FK_CENTRO_ID = c.ID;
